
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/app/_components";
import {Toaster} from 'react-hot-toast'
import { SessionProvider } from "next-auth/react";
import MyProvider from "@/myProviders/myProvider";
import CartProvider from '@/contexts/cartContext'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
      <MyProvider>
        <CartProvider>
          <Navbar />
        <main className="flex-grow ">{children}
             <Toaster position="top-right" reverseOrder={false}/>
        </main>
        <Toaster position="top-right" reverseOrder={false}/>
        <Footer />
        </CartProvider>
      </MyProvider>
       
     
      </body>
    </html>
  );
}
